# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='Linkedin.proto',
  package='linkedinprofile',
  serialized_pb='\n\x0eLinkedin.proto\x12\x0flinkedinprofile\"\xc6\x06\n\x0fLinkedinProfile\x12\x0b\n\x03uid\x18\x01 \x02(\x03\x12\x44\n\rpersonal_info\x18\x02 \x01(\x0b\x32-.linkedinprofile.LinkedinProfile.PersonalInfo\x12:\n\x08his_data\x18\x03 \x01(\x0b\x32(.linkedinprofile.LinkedinProfile.HisData\x12\x10\n\x08overview\x18\x04 \x01(\x0c\x12\x12\n\nspeciality\x18\x05 \x01(\x0c\x12\x0b\n\x03tag\x18\x06 \x03(\x0c\x12\x0c\n\x04\x66tag\x18\x07 \x03(\x0c\x12\x10\n\x08headline\x18\x08 \x01(\x0c\x12\x10\n\x08orig_uid\x18\t \x01(\x0c\x1a\xd1\x01\n\x0cPersonalInfo\x12\x0b\n\x03img\x18\x01 \x01(\x0c\x12\x0c\n\x04name\x18\x02 \x02(\x0c\x12\x0b\n\x03url\x18\x03 \x01(\x0c\x12\x10\n\x08location\x18\x04 \x01(\x0c\x12\x10\n\x08industry\x18\x05 \x01(\x0c\x12\x13\n\x0b\x63onnections\x18\x06 \x01(\x05\x12\x0e\n\x06gender\x18\x07 \x01(\x05\x12\x10\n\x08\x62irthday\x18\x08 \x01(\x0c\x12\r\n\x05\x65mail\x18\t \x01(\x0c\x12\x0c\n\x04\x62log\x18\n \x01(\x0c\x12\x0f\n\x07\x63ontact\x18\x0b \x01(\x0c\x12\x10\n\x08hometown\x18\x0c \x01(\x0c\x1a\xea\x02\n\x07HisData\x12?\n\x03\x65\x64u\x18\x01 \x03(\x0b\x32\x32.linkedinprofile.LinkedinProfile.HisData.Education\x12=\n\x03\x63om\x18\x02 \x03(\x0b\x32\x30.linkedinprofile.LinkedinProfile.HisData.Company\x1am\n\tEducation\x12\x0c\n\x04name\x18\x01 \x02(\x0c\x12\x0e\n\x06year_s\x18\x02 \x01(\x05\x12\x0e\n\x06year_e\x18\x03 \x01(\x05\x12\r\n\x05major\x18\x04 \x01(\x0c\x12\x0e\n\x06\x64\x65gree\x18\x05 \x01(\x0c\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\x0c\x1ap\n\x07\x43ompany\x12\x0c\n\x04name\x18\x01 \x02(\x0c\x12\x0e\n\x06year_s\x18\x02 \x01(\x05\x12\x0e\n\x06year_e\x18\x03 \x01(\x05\x12\x10\n\x08position\x18\x04 \x01(\x0c\x12\x10\n\x08location\x18\x05 \x01(\x0c\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\x0c')




_LINKEDINPROFILE_PERSONALINFO = descriptor.Descriptor(
  name='PersonalInfo',
  full_name='linkedinprofile.LinkedinProfile.PersonalInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='img', full_name='linkedinprofile.LinkedinProfile.PersonalInfo.img', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='name', full_name='linkedinprofile.LinkedinProfile.PersonalInfo.name', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='url', full_name='linkedinprofile.LinkedinProfile.PersonalInfo.url', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='location', full_name='linkedinprofile.LinkedinProfile.PersonalInfo.location', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='industry', full_name='linkedinprofile.LinkedinProfile.PersonalInfo.industry', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='connections', full_name='linkedinprofile.LinkedinProfile.PersonalInfo.connections', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='gender', full_name='linkedinprofile.LinkedinProfile.PersonalInfo.gender', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='birthday', full_name='linkedinprofile.LinkedinProfile.PersonalInfo.birthday', index=7,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='email', full_name='linkedinprofile.LinkedinProfile.PersonalInfo.email', index=8,
      number=9, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='blog', full_name='linkedinprofile.LinkedinProfile.PersonalInfo.blog', index=9,
      number=10, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='contact', full_name='linkedinprofile.LinkedinProfile.PersonalInfo.contact', index=10,
      number=11, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='hometown', full_name='linkedinprofile.LinkedinProfile.PersonalInfo.hometown', index=11,
      number=12, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=300,
  serialized_end=509,
)

_LINKEDINPROFILE_HISDATA_EDUCATION = descriptor.Descriptor(
  name='Education',
  full_name='linkedinprofile.LinkedinProfile.HisData.Education',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='linkedinprofile.LinkedinProfile.HisData.Education.name', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='year_s', full_name='linkedinprofile.LinkedinProfile.HisData.Education.year_s', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='year_e', full_name='linkedinprofile.LinkedinProfile.HisData.Education.year_e', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='major', full_name='linkedinprofile.LinkedinProfile.HisData.Education.major', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='degree', full_name='linkedinprofile.LinkedinProfile.HisData.Education.degree', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='description', full_name='linkedinprofile.LinkedinProfile.HisData.Education.description', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=651,
  serialized_end=760,
)

_LINKEDINPROFILE_HISDATA_COMPANY = descriptor.Descriptor(
  name='Company',
  full_name='linkedinprofile.LinkedinProfile.HisData.Company',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='linkedinprofile.LinkedinProfile.HisData.Company.name', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='year_s', full_name='linkedinprofile.LinkedinProfile.HisData.Company.year_s', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='year_e', full_name='linkedinprofile.LinkedinProfile.HisData.Company.year_e', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='position', full_name='linkedinprofile.LinkedinProfile.HisData.Company.position', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='location', full_name='linkedinprofile.LinkedinProfile.HisData.Company.location', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='description', full_name='linkedinprofile.LinkedinProfile.HisData.Company.description', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=762,
  serialized_end=874,
)

_LINKEDINPROFILE_HISDATA = descriptor.Descriptor(
  name='HisData',
  full_name='linkedinprofile.LinkedinProfile.HisData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='edu', full_name='linkedinprofile.LinkedinProfile.HisData.edu', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='com', full_name='linkedinprofile.LinkedinProfile.HisData.com', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_LINKEDINPROFILE_HISDATA_EDUCATION, _LINKEDINPROFILE_HISDATA_COMPANY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=512,
  serialized_end=874,
)

_LINKEDINPROFILE = descriptor.Descriptor(
  name='LinkedinProfile',
  full_name='linkedinprofile.LinkedinProfile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='uid', full_name='linkedinprofile.LinkedinProfile.uid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='personal_info', full_name='linkedinprofile.LinkedinProfile.personal_info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='his_data', full_name='linkedinprofile.LinkedinProfile.his_data', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='overview', full_name='linkedinprofile.LinkedinProfile.overview', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='speciality', full_name='linkedinprofile.LinkedinProfile.speciality', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='tag', full_name='linkedinprofile.LinkedinProfile.tag', index=5,
      number=6, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ftag', full_name='linkedinprofile.LinkedinProfile.ftag', index=6,
      number=7, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='headline', full_name='linkedinprofile.LinkedinProfile.headline', index=7,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='orig_uid', full_name='linkedinprofile.LinkedinProfile.orig_uid', index=8,
      number=9, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_LINKEDINPROFILE_PERSONALINFO, _LINKEDINPROFILE_HISDATA, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=36,
  serialized_end=874,
)

_LINKEDINPROFILE_PERSONALINFO.containing_type = _LINKEDINPROFILE;
_LINKEDINPROFILE_HISDATA_EDUCATION.containing_type = _LINKEDINPROFILE_HISDATA;
_LINKEDINPROFILE_HISDATA_COMPANY.containing_type = _LINKEDINPROFILE_HISDATA;
_LINKEDINPROFILE_HISDATA.fields_by_name['edu'].message_type = _LINKEDINPROFILE_HISDATA_EDUCATION
_LINKEDINPROFILE_HISDATA.fields_by_name['com'].message_type = _LINKEDINPROFILE_HISDATA_COMPANY
_LINKEDINPROFILE_HISDATA.containing_type = _LINKEDINPROFILE;
_LINKEDINPROFILE.fields_by_name['personal_info'].message_type = _LINKEDINPROFILE_PERSONALINFO
_LINKEDINPROFILE.fields_by_name['his_data'].message_type = _LINKEDINPROFILE_HISDATA
DESCRIPTOR.message_types_by_name['LinkedinProfile'] = _LINKEDINPROFILE

class LinkedinProfile(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class PersonalInfo(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _LINKEDINPROFILE_PERSONALINFO
    
    # @@protoc_insertion_point(class_scope:linkedinprofile.LinkedinProfile.PersonalInfo)
  
  class HisData(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    
    class Education(message.Message):
      __metaclass__ = reflection.GeneratedProtocolMessageType
      DESCRIPTOR = _LINKEDINPROFILE_HISDATA_EDUCATION
      
      # @@protoc_insertion_point(class_scope:linkedinprofile.LinkedinProfile.HisData.Education)
    
    class Company(message.Message):
      __metaclass__ = reflection.GeneratedProtocolMessageType
      DESCRIPTOR = _LINKEDINPROFILE_HISDATA_COMPANY
      
      # @@protoc_insertion_point(class_scope:linkedinprofile.LinkedinProfile.HisData.Company)
    DESCRIPTOR = _LINKEDINPROFILE_HISDATA
    
    # @@protoc_insertion_point(class_scope:linkedinprofile.LinkedinProfile.HisData)
  DESCRIPTOR = _LINKEDINPROFILE
  
  # @@protoc_insertion_point(class_scope:linkedinprofile.LinkedinProfile)

# @@protoc_insertion_point(module_scope)
