# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import SimpleResume_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='Resume.proto',
  package='',
  serialized_pb='\n\x0cResume.proto\x1a\x12SimpleResume.proto\"r\n\tEducation\x12\x11\n\tschool_id\x18\x01 \x02(\x05\x12\x13\n\x0bschool_name\x18\x02 \x02(\x0c\x12\x0e\n\x06year_s\x18\x03 \x01(\x0c\x12\x0e\n\x06year_e\x18\x04 \x01(\x0c\x12\r\n\x05major\x18\x05 \x01(\x0c\x12\x0e\n\x06\x64\x65gree\x18\x06 \x01(\x0c\"w\n\x04Work\x12\x12\n\ncompany_id\x18\x01 \x02(\x05\x12\x14\n\x0c\x63ompany_name\x18\x02 \x02(\x0c\x12\x0e\n\x06year_s\x18\x03 \x01(\x0c\x12\x0e\n\x06year_e\x18\x04 \x01(\x0c\x12\x10\n\x08position\x18\x05 \x01(\x0c\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\x0c\"9\n\x0b\x45ndorsement\x12\x0b\n\x03zid\x18\x01 \x02(\x05\x12\x0f\n\x07\x63ontent\x18\x02 \x02(\x0c\x12\x0c\n\x04\x64\x61te\x18\x03 \x02(\x0c\"\xdf\x01\n\x06Resume\x12!\n\nbasic_info\x18\x01 \x02(\x0b\x32\r.SimpleResume\x12\x1d\n\teducation\x18\x02 \x03(\x0b\x32\n.Education\x12\x13\n\x04work\x18\x03 \x03(\x0b\x32\x05.Work\x12!\n\x0b\x65ndorsement\x18\x04 \x03(\x0b\x32\x0c.Endorsement\x12\x19\n\x11\x62\x61sic_info_filled\x18\x05 \x01(\x08\x12\x18\n\x10\x65\x64ucation_filled\x18\x06 \x01(\x08\x12\x13\n\x0bwork_filled\x18\x07 \x01(\x08\x12\x11\n\tindexable\x18\x08 \x01(\x05')




_EDUCATION = descriptor.Descriptor(
  name='Education',
  full_name='Education',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='school_id', full_name='Education.school_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='school_name', full_name='Education.school_name', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='year_s', full_name='Education.year_s', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='year_e', full_name='Education.year_e', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='major', full_name='Education.major', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='degree', full_name='Education.degree', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=36,
  serialized_end=150,
)


_WORK = descriptor.Descriptor(
  name='Work',
  full_name='Work',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='company_id', full_name='Work.company_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='company_name', full_name='Work.company_name', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='year_s', full_name='Work.year_s', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='year_e', full_name='Work.year_e', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='position', full_name='Work.position', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='description', full_name='Work.description', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=152,
  serialized_end=271,
)


_ENDORSEMENT = descriptor.Descriptor(
  name='Endorsement',
  full_name='Endorsement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='zid', full_name='Endorsement.zid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='content', full_name='Endorsement.content', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='date', full_name='Endorsement.date', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=273,
  serialized_end=330,
)


_RESUME = descriptor.Descriptor(
  name='Resume',
  full_name='Resume',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='basic_info', full_name='Resume.basic_info', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='education', full_name='Resume.education', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='work', full_name='Resume.work', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='endorsement', full_name='Resume.endorsement', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='basic_info_filled', full_name='Resume.basic_info_filled', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='education_filled', full_name='Resume.education_filled', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='work_filled', full_name='Resume.work_filled', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='indexable', full_name='Resume.indexable', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=333,
  serialized_end=556,
)

_RESUME.fields_by_name['basic_info'].message_type = SimpleResume_pb2._SIMPLERESUME
_RESUME.fields_by_name['education'].message_type = _EDUCATION
_RESUME.fields_by_name['work'].message_type = _WORK
_RESUME.fields_by_name['endorsement'].message_type = _ENDORSEMENT
DESCRIPTOR.message_types_by_name['Education'] = _EDUCATION
DESCRIPTOR.message_types_by_name['Work'] = _WORK
DESCRIPTOR.message_types_by_name['Endorsement'] = _ENDORSEMENT
DESCRIPTOR.message_types_by_name['Resume'] = _RESUME

class Education(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EDUCATION
  
  # @@protoc_insertion_point(class_scope:Education)

class Work(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WORK
  
  # @@protoc_insertion_point(class_scope:Work)

class Endorsement(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ENDORSEMENT
  
  # @@protoc_insertion_point(class_scope:Endorsement)

class Resume(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RESUME
  
  # @@protoc_insertion_point(class_scope:Resume)

# @@protoc_insertion_point(module_scope)
