# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='SavedCandidateProto.proto',
  package='',
  serialized_pb='\n\x19SavedCandidateProto.proto\"*\n\rBasicJobProto\x12\n\n\x02id\x18\x01 \x02(\x05\x12\r\n\x05title\x18\x02 \x02(\x0c\"\x97\x01\n\x13SavedCandidateProto\x12\x0b\n\x03zid\x18\x01 \x02(\x05\x12\x0f\n\x07network\x18\x02 \x02(\x0c\x12\x12\n\nprofile_id\x18\x03 \x02(\x0c\x12\x12\n\nsaved_time\x18\x04 \x02(\x03\x12\r\n\x05notes\x18\x05 \x01(\x0c\x12\x1b\n\x03job\x18\x06 \x03(\x0b\x32\x0e.BasicJobProto\x12\x0e\n\x06status\x18\x07 \x01(\x0c')




_BASICJOBPROTO = descriptor.Descriptor(
  name='BasicJobProto',
  full_name='BasicJobProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='BasicJobProto.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='title', full_name='BasicJobProto.title', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=29,
  serialized_end=71,
)


_SAVEDCANDIDATEPROTO = descriptor.Descriptor(
  name='SavedCandidateProto',
  full_name='SavedCandidateProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='zid', full_name='SavedCandidateProto.zid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='network', full_name='SavedCandidateProto.network', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='profile_id', full_name='SavedCandidateProto.profile_id', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='saved_time', full_name='SavedCandidateProto.saved_time', index=3,
      number=4, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='notes', full_name='SavedCandidateProto.notes', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='job', full_name='SavedCandidateProto.job', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='status', full_name='SavedCandidateProto.status', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=74,
  serialized_end=225,
)

_SAVEDCANDIDATEPROTO.fields_by_name['job'].message_type = _BASICJOBPROTO
DESCRIPTOR.message_types_by_name['BasicJobProto'] = _BASICJOBPROTO
DESCRIPTOR.message_types_by_name['SavedCandidateProto'] = _SAVEDCANDIDATEPROTO

class BasicJobProto(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BASICJOBPROTO
  
  # @@protoc_insertion_point(class_scope:BasicJobProto)

class SavedCandidateProto(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SAVEDCANDIDATEPROTO
  
  # @@protoc_insertion_point(class_scope:SavedCandidateProto)

# @@protoc_insertion_point(module_scope)
