# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='UserSearchResult.proto',
  package='user_search',
  serialized_pb='\n\x16UserSearchResult.proto\x12\x0buser_search\"\x92\x03\n\x10UserSearchResult\x12\x0e\n\x06offset\x18\x01 \x01(\x05\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\x12\x17\n\x0ftotal_estimated\x18\x03 \x01(\x05\x12=\n\x0bresult_item\x18\x04 \x03(\x0b\x32(.user_search.UserSearchResult.ResultItem\x12;\n\nstats_item\x18\x05 \x03(\x0b\x32\'.user_search.UserSearchResult.StatsItem\x12\x18\n\x10total_pre_cutoff\x18\x06 \x01(\x05\x1aS\n\nResultItem\x12\x0b\n\x03uid\x18\x01 \x01(\x03\x12\r\n\x05score\x18\x02 \x01(\x01\x12\x15\n\rlink_distance\x18\x03 \x01(\x05\x12\x12\n\ndebug_data\x18\x04 \x01(\x0c\x1a[\n\tStatsItem\x12\x12\n\nstats_type\x18\x01 \x01(\x0c\x12\x11\n\tstats_key\x18\x02 \x01(\x04\x12\x12\n\nstats_name\x18\x04 \x01(\x0c\x12\x13\n\x0bstats_value\x18\x03 \x01(\x04')




_USERSEARCHRESULT_RESULTITEM = descriptor.Descriptor(
  name='ResultItem',
  full_name='user_search.UserSearchResult.ResultItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='uid', full_name='user_search.UserSearchResult.ResultItem.uid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='score', full_name='user_search.UserSearchResult.ResultItem.score', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='link_distance', full_name='user_search.UserSearchResult.ResultItem.link_distance', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='debug_data', full_name='user_search.UserSearchResult.ResultItem.debug_data', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=266,
  serialized_end=349,
)

_USERSEARCHRESULT_STATSITEM = descriptor.Descriptor(
  name='StatsItem',
  full_name='user_search.UserSearchResult.StatsItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='stats_type', full_name='user_search.UserSearchResult.StatsItem.stats_type', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='stats_key', full_name='user_search.UserSearchResult.StatsItem.stats_key', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='stats_name', full_name='user_search.UserSearchResult.StatsItem.stats_name', index=2,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='stats_value', full_name='user_search.UserSearchResult.StatsItem.stats_value', index=3,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=351,
  serialized_end=442,
)

_USERSEARCHRESULT = descriptor.Descriptor(
  name='UserSearchResult',
  full_name='user_search.UserSearchResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='offset', full_name='user_search.UserSearchResult.offset', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='count', full_name='user_search.UserSearchResult.count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='total_estimated', full_name='user_search.UserSearchResult.total_estimated', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='result_item', full_name='user_search.UserSearchResult.result_item', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='stats_item', full_name='user_search.UserSearchResult.stats_item', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='total_pre_cutoff', full_name='user_search.UserSearchResult.total_pre_cutoff', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_USERSEARCHRESULT_RESULTITEM, _USERSEARCHRESULT_STATSITEM, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=40,
  serialized_end=442,
)

_USERSEARCHRESULT_RESULTITEM.containing_type = _USERSEARCHRESULT;
_USERSEARCHRESULT_STATSITEM.containing_type = _USERSEARCHRESULT;
_USERSEARCHRESULT.fields_by_name['result_item'].message_type = _USERSEARCHRESULT_RESULTITEM
_USERSEARCHRESULT.fields_by_name['stats_item'].message_type = _USERSEARCHRESULT_STATSITEM
DESCRIPTOR.message_types_by_name['UserSearchResult'] = _USERSEARCHRESULT

class UserSearchResult(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class ResultItem(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _USERSEARCHRESULT_RESULTITEM
    
    # @@protoc_insertion_point(class_scope:user_search.UserSearchResult.ResultItem)
  
  class StatsItem(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _USERSEARCHRESULT_STATSITEM
    
    # @@protoc_insertion_point(class_scope:user_search.UserSearchResult.StatsItem)
  DESCRIPTOR = _USERSEARCHRESULT
  
  # @@protoc_insertion_point(class_scope:user_search.UserSearchResult)

# @@protoc_insertion_point(module_scope)
