# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='UserSearchQuery.proto',
  package='user_search',
  serialized_pb='\n\x15UserSearchQuery.proto\x12\x0buser_search\"\xf2\x06\n\x11PbUserSearchQuery\x12\x0e\n\x06offset\x18\x01 \x01(\x05\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\x12\x19\n\x11xapian_query_blob\x18\x03 \x02(\x0c\x12:\n\tterm_info\x18\x18 \x03(\x0b\x32\'.user_search.PbUserSearchQuery.TermInfo\x12\x15\n\rcore_term_num\x18\x17 \x01(\x05\x12\x14\n\x0csearcher_uid\x18\x05 \x01(\x03\x12\x0e\n\x06\x64\x31_uid\x18\x06 \x03(\x03\x12\x0e\n\x06\x64\x32_uid\x18\x07 \x03(\x03\x12\x38\n\x02te\x18\x08 \x03(\x0b\x32,.user_search.PbUserSearchQuery.TermExpansion\x12\x14\n\x0cranking_type\x18\t \x01(\x05\x12O\n\x14link_distance_filter\x18\n \x01(\x0b\x32\x31.user_search.PbUserSearchQuery.LinkDistanceFilter\x12\x16\n\x0estats_com_term\x18\r \x03(\x04\x12\x16\n\x0estats_job_term\x18\x0e \x03(\x04\x12\x16\n\x0estats_tag_term\x18\x0f \x03(\x04\x12\x16\n\x0estats_sch_term\x18\x10 \x03(\x04\x12\x1d\n\x15searcher_company_name\x18\x13 \x01(\x0c\x12#\n\x1b\x66ilter_company_1du_contacts\x18\x14 \x01(\x08\x12\'\n\x1f\x66ilter_non_company_1du_contacts\x18\x15 \x01(\x08\x12\x11\n\ttask_type\x18\x11 \x01(\x05\x12\r\n\x05\x64\x65\x62ug\x18\x12 \x01(\x08\x12\x16\n\x0eversion_number\x18\x16 \x01(\r\x12\x1a\n\x12max_result_set_num\x18\x1e \x01(\x03\x12\x1c\n\x14\x64isable_score_filter\x18\x1f \x01(\r\x1a,\n\rTermExpansion\x12\x0c\n\x04term\x18\x01 \x02(\x0c\x12\r\n\x05\x65term\x18\x02 \x03(\x0c\x1aJ\n\x12LinkDistanceFilter\x12\x10\n\x08link_1du\x18\x01 \x01(\x08\x12\x10\n\x08link_2du\x18\x02 \x01(\x08\x12\x10\n\x08link_xdu\x18\x03 \x01(\x08\x1a>\n\x08TermInfo\x12\x0f\n\x07term_id\x18\x01 \x01(\x04\x12\x0f\n\x07payload\x18\x02 \x01(\r\x12\x10\n\x08position\x18\x03 \x03(\r')




_PBUSERSEARCHQUERY_TERMEXPANSION = descriptor.Descriptor(
  name='TermExpansion',
  full_name='user_search.PbUserSearchQuery.TermExpansion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='term', full_name='user_search.PbUserSearchQuery.TermExpansion.term', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='eterm', full_name='user_search.PbUserSearchQuery.TermExpansion.eterm', index=1,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=737,
  serialized_end=781,
)

_PBUSERSEARCHQUERY_LINKDISTANCEFILTER = descriptor.Descriptor(
  name='LinkDistanceFilter',
  full_name='user_search.PbUserSearchQuery.LinkDistanceFilter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='link_1du', full_name='user_search.PbUserSearchQuery.LinkDistanceFilter.link_1du', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='link_2du', full_name='user_search.PbUserSearchQuery.LinkDistanceFilter.link_2du', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='link_xdu', full_name='user_search.PbUserSearchQuery.LinkDistanceFilter.link_xdu', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=783,
  serialized_end=857,
)

_PBUSERSEARCHQUERY_TERMINFO = descriptor.Descriptor(
  name='TermInfo',
  full_name='user_search.PbUserSearchQuery.TermInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='term_id', full_name='user_search.PbUserSearchQuery.TermInfo.term_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='payload', full_name='user_search.PbUserSearchQuery.TermInfo.payload', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='position', full_name='user_search.PbUserSearchQuery.TermInfo.position', index=2,
      number=3, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=859,
  serialized_end=921,
)

_PBUSERSEARCHQUERY = descriptor.Descriptor(
  name='PbUserSearchQuery',
  full_name='user_search.PbUserSearchQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='offset', full_name='user_search.PbUserSearchQuery.offset', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='count', full_name='user_search.PbUserSearchQuery.count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='xapian_query_blob', full_name='user_search.PbUserSearchQuery.xapian_query_blob', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='term_info', full_name='user_search.PbUserSearchQuery.term_info', index=3,
      number=24, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='core_term_num', full_name='user_search.PbUserSearchQuery.core_term_num', index=4,
      number=23, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='searcher_uid', full_name='user_search.PbUserSearchQuery.searcher_uid', index=5,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='d1_uid', full_name='user_search.PbUserSearchQuery.d1_uid', index=6,
      number=6, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='d2_uid', full_name='user_search.PbUserSearchQuery.d2_uid', index=7,
      number=7, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='te', full_name='user_search.PbUserSearchQuery.te', index=8,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ranking_type', full_name='user_search.PbUserSearchQuery.ranking_type', index=9,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='link_distance_filter', full_name='user_search.PbUserSearchQuery.link_distance_filter', index=10,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='stats_com_term', full_name='user_search.PbUserSearchQuery.stats_com_term', index=11,
      number=13, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='stats_job_term', full_name='user_search.PbUserSearchQuery.stats_job_term', index=12,
      number=14, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='stats_tag_term', full_name='user_search.PbUserSearchQuery.stats_tag_term', index=13,
      number=15, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='stats_sch_term', full_name='user_search.PbUserSearchQuery.stats_sch_term', index=14,
      number=16, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='searcher_company_name', full_name='user_search.PbUserSearchQuery.searcher_company_name', index=15,
      number=19, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='filter_company_1du_contacts', full_name='user_search.PbUserSearchQuery.filter_company_1du_contacts', index=16,
      number=20, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='filter_non_company_1du_contacts', full_name='user_search.PbUserSearchQuery.filter_non_company_1du_contacts', index=17,
      number=21, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='task_type', full_name='user_search.PbUserSearchQuery.task_type', index=18,
      number=17, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='debug', full_name='user_search.PbUserSearchQuery.debug', index=19,
      number=18, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='version_number', full_name='user_search.PbUserSearchQuery.version_number', index=20,
      number=22, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='max_result_set_num', full_name='user_search.PbUserSearchQuery.max_result_set_num', index=21,
      number=30, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='disable_score_filter', full_name='user_search.PbUserSearchQuery.disable_score_filter', index=22,
      number=31, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PBUSERSEARCHQUERY_TERMEXPANSION, _PBUSERSEARCHQUERY_LINKDISTANCEFILTER, _PBUSERSEARCHQUERY_TERMINFO, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=39,
  serialized_end=921,
)

_PBUSERSEARCHQUERY_TERMEXPANSION.containing_type = _PBUSERSEARCHQUERY;
_PBUSERSEARCHQUERY_LINKDISTANCEFILTER.containing_type = _PBUSERSEARCHQUERY;
_PBUSERSEARCHQUERY_TERMINFO.containing_type = _PBUSERSEARCHQUERY;
_PBUSERSEARCHQUERY.fields_by_name['term_info'].message_type = _PBUSERSEARCHQUERY_TERMINFO
_PBUSERSEARCHQUERY.fields_by_name['te'].message_type = _PBUSERSEARCHQUERY_TERMEXPANSION
_PBUSERSEARCHQUERY.fields_by_name['link_distance_filter'].message_type = _PBUSERSEARCHQUERY_LINKDISTANCEFILTER
DESCRIPTOR.message_types_by_name['PbUserSearchQuery'] = _PBUSERSEARCHQUERY

class PbUserSearchQuery(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class TermExpansion(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _PBUSERSEARCHQUERY_TERMEXPANSION
    
    # @@protoc_insertion_point(class_scope:user_search.PbUserSearchQuery.TermExpansion)
  
  class LinkDistanceFilter(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _PBUSERSEARCHQUERY_LINKDISTANCEFILTER
    
    # @@protoc_insertion_point(class_scope:user_search.PbUserSearchQuery.LinkDistanceFilter)
  
  class TermInfo(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _PBUSERSEARCHQUERY_TERMINFO
    
    # @@protoc_insertion_point(class_scope:user_search.PbUserSearchQuery.TermInfo)
  DESCRIPTOR = _PBUSERSEARCHQUERY
  
  # @@protoc_insertion_point(class_scope:user_search.PbUserSearchQuery)

# @@protoc_insertion_point(module_scope)
