// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "JobSearchQuery.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace job_search {

namespace {

const ::google::protobuf::Descriptor* PbJobSearchQuery_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PbJobSearchQuery_reflection_ = NULL;
const ::google::protobuf::Descriptor* PbJobSearchQuery_TermExpansion_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PbJobSearchQuery_TermExpansion_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_JobSearchQuery_2eproto() {
  protobuf_AddDesc_JobSearchQuery_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "JobSearchQuery.proto");
  GOOGLE_CHECK(file != NULL);
  PbJobSearchQuery_descriptor_ = file->message_type(0);
  static const int PbJobSearchQuery_offsets_[14] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PbJobSearchQuery, offset_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PbJobSearchQuery, count_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PbJobSearchQuery, xapian_query_blob_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PbJobSearchQuery, searcher_uid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PbJobSearchQuery, d1_uid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PbJobSearchQuery, d2_uid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PbJobSearchQuery, te_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PbJobSearchQuery, search_type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PbJobSearchQuery, stats_com_term_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PbJobSearchQuery, stats_job_term_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PbJobSearchQuery, stats_tag_term_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PbJobSearchQuery, stats_sch_term_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PbJobSearchQuery, task_type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PbJobSearchQuery, debug_),
  };
  PbJobSearchQuery_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      PbJobSearchQuery_descriptor_,
      PbJobSearchQuery::default_instance_,
      PbJobSearchQuery_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PbJobSearchQuery, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PbJobSearchQuery, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(PbJobSearchQuery));
  PbJobSearchQuery_TermExpansion_descriptor_ = PbJobSearchQuery_descriptor_->nested_type(0);
  static const int PbJobSearchQuery_TermExpansion_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PbJobSearchQuery_TermExpansion, term_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PbJobSearchQuery_TermExpansion, eterm_),
  };
  PbJobSearchQuery_TermExpansion_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      PbJobSearchQuery_TermExpansion_descriptor_,
      PbJobSearchQuery_TermExpansion::default_instance_,
      PbJobSearchQuery_TermExpansion_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PbJobSearchQuery_TermExpansion, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PbJobSearchQuery_TermExpansion, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(PbJobSearchQuery_TermExpansion));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_JobSearchQuery_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    PbJobSearchQuery_descriptor_, &PbJobSearchQuery::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    PbJobSearchQuery_TermExpansion_descriptor_, &PbJobSearchQuery_TermExpansion::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_JobSearchQuery_2eproto() {
  delete PbJobSearchQuery::default_instance_;
  delete PbJobSearchQuery_reflection_;
  delete PbJobSearchQuery_TermExpansion::default_instance_;
  delete PbJobSearchQuery_TermExpansion_reflection_;
}

void protobuf_AddDesc_JobSearchQuery_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\024JobSearchQuery.proto\022\njob_search\"\377\002\n\020P"
    "bJobSearchQuery\022\016\n\006offset\030\001 \001(\005\022\r\n\005count"
    "\030\002 \001(\005\022\031\n\021xapian_query_blob\030\003 \002(\014\022\024\n\014sea"
    "rcher_uid\030\005 \001(\003\022\016\n\006d1_uid\030\006 \003(\003\022\016\n\006d2_ui"
    "d\030\007 \003(\003\0226\n\002te\030\010 \003(\0132*.job_search.PbJobSe"
    "archQuery.TermExpansion\022\023\n\013search_type\030\t"
    " \001(\005\022\026\n\016stats_com_term\030\r \003(\004\022\026\n\016stats_jo"
    "b_term\030\016 \003(\004\022\026\n\016stats_tag_term\030\017 \003(\004\022\026\n\016"
    "stats_sch_term\030\020 \003(\004\022\021\n\ttask_type\030\021 \001(\005\022"
    "\r\n\005debug\030\022 \001(\010\032,\n\rTermExpansion\022\014\n\004term\030"
    "\001 \002(\014\022\r\n\005eterm\030\002 \003(\014", 420);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "JobSearchQuery.proto", &protobuf_RegisterTypes);
  PbJobSearchQuery::default_instance_ = new PbJobSearchQuery();
  PbJobSearchQuery_TermExpansion::default_instance_ = new PbJobSearchQuery_TermExpansion();
  PbJobSearchQuery::default_instance_->InitAsDefaultInstance();
  PbJobSearchQuery_TermExpansion::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_JobSearchQuery_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_JobSearchQuery_2eproto {
  StaticDescriptorInitializer_JobSearchQuery_2eproto() {
    protobuf_AddDesc_JobSearchQuery_2eproto();
  }
} static_descriptor_initializer_JobSearchQuery_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int PbJobSearchQuery_TermExpansion::kTermFieldNumber;
const int PbJobSearchQuery_TermExpansion::kEtermFieldNumber;
#endif  // !_MSC_VER

PbJobSearchQuery_TermExpansion::PbJobSearchQuery_TermExpansion()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void PbJobSearchQuery_TermExpansion::InitAsDefaultInstance() {
}

PbJobSearchQuery_TermExpansion::PbJobSearchQuery_TermExpansion(const PbJobSearchQuery_TermExpansion& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void PbJobSearchQuery_TermExpansion::SharedCtor() {
  _cached_size_ = 0;
  term_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PbJobSearchQuery_TermExpansion::~PbJobSearchQuery_TermExpansion() {
  SharedDtor();
}

void PbJobSearchQuery_TermExpansion::SharedDtor() {
  if (term_ != &::google::protobuf::internal::kEmptyString) {
    delete term_;
  }
  if (this != default_instance_) {
  }
}

void PbJobSearchQuery_TermExpansion::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PbJobSearchQuery_TermExpansion::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PbJobSearchQuery_TermExpansion_descriptor_;
}

const PbJobSearchQuery_TermExpansion& PbJobSearchQuery_TermExpansion::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_JobSearchQuery_2eproto();  return *default_instance_;
}

PbJobSearchQuery_TermExpansion* PbJobSearchQuery_TermExpansion::default_instance_ = NULL;

PbJobSearchQuery_TermExpansion* PbJobSearchQuery_TermExpansion::New() const {
  return new PbJobSearchQuery_TermExpansion;
}

void PbJobSearchQuery_TermExpansion::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_term()) {
      if (term_ != &::google::protobuf::internal::kEmptyString) {
        term_->clear();
      }
    }
  }
  eterm_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool PbJobSearchQuery_TermExpansion::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required bytes term = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_term()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_eterm;
        break;
      }
      
      // repeated bytes eterm = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_eterm:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->add_eterm()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_eterm;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void PbJobSearchQuery_TermExpansion::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required bytes term = 1;
  if (has_term()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      1, this->term(), output);
  }
  
  // repeated bytes eterm = 2;
  for (int i = 0; i < this->eterm_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      2, this->eterm(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* PbJobSearchQuery_TermExpansion::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required bytes term = 1;
  if (has_term()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->term(), target);
  }
  
  // repeated bytes eterm = 2;
  for (int i = 0; i < this->eterm_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteBytesToArray(2, this->eterm(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int PbJobSearchQuery_TermExpansion::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required bytes term = 1;
    if (has_term()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->term());
    }
    
  }
  // repeated bytes eterm = 2;
  total_size += 1 * this->eterm_size();
  for (int i = 0; i < this->eterm_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::BytesSize(
      this->eterm(i));
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PbJobSearchQuery_TermExpansion::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const PbJobSearchQuery_TermExpansion* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const PbJobSearchQuery_TermExpansion*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void PbJobSearchQuery_TermExpansion::MergeFrom(const PbJobSearchQuery_TermExpansion& from) {
  GOOGLE_CHECK_NE(&from, this);
  eterm_.MergeFrom(from.eterm_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_term()) {
      set_term(from.term());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void PbJobSearchQuery_TermExpansion::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PbJobSearchQuery_TermExpansion::CopyFrom(const PbJobSearchQuery_TermExpansion& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PbJobSearchQuery_TermExpansion::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  
  return true;
}

void PbJobSearchQuery_TermExpansion::Swap(PbJobSearchQuery_TermExpansion* other) {
  if (other != this) {
    std::swap(term_, other->term_);
    eterm_.Swap(&other->eterm_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata PbJobSearchQuery_TermExpansion::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PbJobSearchQuery_TermExpansion_descriptor_;
  metadata.reflection = PbJobSearchQuery_TermExpansion_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int PbJobSearchQuery::kOffsetFieldNumber;
const int PbJobSearchQuery::kCountFieldNumber;
const int PbJobSearchQuery::kXapianQueryBlobFieldNumber;
const int PbJobSearchQuery::kSearcherUidFieldNumber;
const int PbJobSearchQuery::kD1UidFieldNumber;
const int PbJobSearchQuery::kD2UidFieldNumber;
const int PbJobSearchQuery::kTeFieldNumber;
const int PbJobSearchQuery::kSearchTypeFieldNumber;
const int PbJobSearchQuery::kStatsComTermFieldNumber;
const int PbJobSearchQuery::kStatsJobTermFieldNumber;
const int PbJobSearchQuery::kStatsTagTermFieldNumber;
const int PbJobSearchQuery::kStatsSchTermFieldNumber;
const int PbJobSearchQuery::kTaskTypeFieldNumber;
const int PbJobSearchQuery::kDebugFieldNumber;
#endif  // !_MSC_VER

PbJobSearchQuery::PbJobSearchQuery()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void PbJobSearchQuery::InitAsDefaultInstance() {
}

PbJobSearchQuery::PbJobSearchQuery(const PbJobSearchQuery& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void PbJobSearchQuery::SharedCtor() {
  _cached_size_ = 0;
  offset_ = 0;
  count_ = 0;
  xapian_query_blob_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  searcher_uid_ = GOOGLE_LONGLONG(0);
  search_type_ = 0;
  task_type_ = 0;
  debug_ = false;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PbJobSearchQuery::~PbJobSearchQuery() {
  SharedDtor();
}

void PbJobSearchQuery::SharedDtor() {
  if (xapian_query_blob_ != &::google::protobuf::internal::kEmptyString) {
    delete xapian_query_blob_;
  }
  if (this != default_instance_) {
  }
}

void PbJobSearchQuery::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PbJobSearchQuery::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PbJobSearchQuery_descriptor_;
}

const PbJobSearchQuery& PbJobSearchQuery::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_JobSearchQuery_2eproto();  return *default_instance_;
}

PbJobSearchQuery* PbJobSearchQuery::default_instance_ = NULL;

PbJobSearchQuery* PbJobSearchQuery::New() const {
  return new PbJobSearchQuery;
}

void PbJobSearchQuery::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    offset_ = 0;
    count_ = 0;
    if (has_xapian_query_blob()) {
      if (xapian_query_blob_ != &::google::protobuf::internal::kEmptyString) {
        xapian_query_blob_->clear();
      }
    }
    searcher_uid_ = GOOGLE_LONGLONG(0);
    search_type_ = 0;
  }
  if (_has_bits_[12 / 32] & (0xffu << (12 % 32))) {
    task_type_ = 0;
    debug_ = false;
  }
  d1_uid_.Clear();
  d2_uid_.Clear();
  te_.Clear();
  stats_com_term_.Clear();
  stats_job_term_.Clear();
  stats_tag_term_.Clear();
  stats_sch_term_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool PbJobSearchQuery::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 offset = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &offset_)));
          set_has_offset();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_count;
        break;
      }
      
      // optional int32 count = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_count:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &count_)));
          set_has_count();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_xapian_query_blob;
        break;
      }
      
      // required bytes xapian_query_blob = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_xapian_query_blob:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_xapian_query_blob()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(40)) goto parse_searcher_uid;
        break;
      }
      
      // optional int64 searcher_uid = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_searcher_uid:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &searcher_uid_)));
          set_has_searcher_uid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(48)) goto parse_d1_uid;
        break;
      }
      
      // repeated int64 d1_uid = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_d1_uid:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 1, 48, input, this->mutable_d1_uid())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, this->mutable_d1_uid())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(48)) goto parse_d1_uid;
        if (input->ExpectTag(56)) goto parse_d2_uid;
        break;
      }
      
      // repeated int64 d2_uid = 7;
      case 7: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_d2_uid:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 1, 56, input, this->mutable_d2_uid())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, this->mutable_d2_uid())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(56)) goto parse_d2_uid;
        if (input->ExpectTag(66)) goto parse_te;
        break;
      }
      
      // repeated .job_search.PbJobSearchQuery.TermExpansion te = 8;
      case 8: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_te:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_te()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(66)) goto parse_te;
        if (input->ExpectTag(72)) goto parse_search_type;
        break;
      }
      
      // optional int32 search_type = 9;
      case 9: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_search_type:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &search_type_)));
          set_has_search_type();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(104)) goto parse_stats_com_term;
        break;
      }
      
      // repeated uint64 stats_com_term = 13;
      case 13: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_stats_com_term:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 1, 104, input, this->mutable_stats_com_term())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, this->mutable_stats_com_term())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(104)) goto parse_stats_com_term;
        if (input->ExpectTag(112)) goto parse_stats_job_term;
        break;
      }
      
      // repeated uint64 stats_job_term = 14;
      case 14: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_stats_job_term:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 1, 112, input, this->mutable_stats_job_term())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, this->mutable_stats_job_term())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(112)) goto parse_stats_job_term;
        if (input->ExpectTag(120)) goto parse_stats_tag_term;
        break;
      }
      
      // repeated uint64 stats_tag_term = 15;
      case 15: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_stats_tag_term:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 1, 120, input, this->mutable_stats_tag_term())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, this->mutable_stats_tag_term())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(120)) goto parse_stats_tag_term;
        if (input->ExpectTag(128)) goto parse_stats_sch_term;
        break;
      }
      
      // repeated uint64 stats_sch_term = 16;
      case 16: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_stats_sch_term:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 2, 128, input, this->mutable_stats_sch_term())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, this->mutable_stats_sch_term())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(128)) goto parse_stats_sch_term;
        if (input->ExpectTag(136)) goto parse_task_type;
        break;
      }
      
      // optional int32 task_type = 17;
      case 17: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_task_type:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &task_type_)));
          set_has_task_type();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(144)) goto parse_debug;
        break;
      }
      
      // optional bool debug = 18;
      case 18: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_debug:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &debug_)));
          set_has_debug();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void PbJobSearchQuery::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional int32 offset = 1;
  if (has_offset()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->offset(), output);
  }
  
  // optional int32 count = 2;
  if (has_count()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->count(), output);
  }
  
  // required bytes xapian_query_blob = 3;
  if (has_xapian_query_blob()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      3, this->xapian_query_blob(), output);
  }
  
  // optional int64 searcher_uid = 5;
  if (has_searcher_uid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(5, this->searcher_uid(), output);
  }
  
  // repeated int64 d1_uid = 6;
  for (int i = 0; i < this->d1_uid_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(
      6, this->d1_uid(i), output);
  }
  
  // repeated int64 d2_uid = 7;
  for (int i = 0; i < this->d2_uid_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(
      7, this->d2_uid(i), output);
  }
  
  // repeated .job_search.PbJobSearchQuery.TermExpansion te = 8;
  for (int i = 0; i < this->te_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      8, this->te(i), output);
  }
  
  // optional int32 search_type = 9;
  if (has_search_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(9, this->search_type(), output);
  }
  
  // repeated uint64 stats_com_term = 13;
  for (int i = 0; i < this->stats_com_term_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(
      13, this->stats_com_term(i), output);
  }
  
  // repeated uint64 stats_job_term = 14;
  for (int i = 0; i < this->stats_job_term_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(
      14, this->stats_job_term(i), output);
  }
  
  // repeated uint64 stats_tag_term = 15;
  for (int i = 0; i < this->stats_tag_term_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(
      15, this->stats_tag_term(i), output);
  }
  
  // repeated uint64 stats_sch_term = 16;
  for (int i = 0; i < this->stats_sch_term_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(
      16, this->stats_sch_term(i), output);
  }
  
  // optional int32 task_type = 17;
  if (has_task_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(17, this->task_type(), output);
  }
  
  // optional bool debug = 18;
  if (has_debug()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(18, this->debug(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* PbJobSearchQuery::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional int32 offset = 1;
  if (has_offset()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->offset(), target);
  }
  
  // optional int32 count = 2;
  if (has_count()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->count(), target);
  }
  
  // required bytes xapian_query_blob = 3;
  if (has_xapian_query_blob()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        3, this->xapian_query_blob(), target);
  }
  
  // optional int64 searcher_uid = 5;
  if (has_searcher_uid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(5, this->searcher_uid(), target);
  }
  
  // repeated int64 d1_uid = 6;
  for (int i = 0; i < this->d1_uid_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt64ToArray(6, this->d1_uid(i), target);
  }
  
  // repeated int64 d2_uid = 7;
  for (int i = 0; i < this->d2_uid_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt64ToArray(7, this->d2_uid(i), target);
  }
  
  // repeated .job_search.PbJobSearchQuery.TermExpansion te = 8;
  for (int i = 0; i < this->te_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        8, this->te(i), target);
  }
  
  // optional int32 search_type = 9;
  if (has_search_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(9, this->search_type(), target);
  }
  
  // repeated uint64 stats_com_term = 13;
  for (int i = 0; i < this->stats_com_term_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteUInt64ToArray(13, this->stats_com_term(i), target);
  }
  
  // repeated uint64 stats_job_term = 14;
  for (int i = 0; i < this->stats_job_term_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteUInt64ToArray(14, this->stats_job_term(i), target);
  }
  
  // repeated uint64 stats_tag_term = 15;
  for (int i = 0; i < this->stats_tag_term_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteUInt64ToArray(15, this->stats_tag_term(i), target);
  }
  
  // repeated uint64 stats_sch_term = 16;
  for (int i = 0; i < this->stats_sch_term_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteUInt64ToArray(16, this->stats_sch_term(i), target);
  }
  
  // optional int32 task_type = 17;
  if (has_task_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(17, this->task_type(), target);
  }
  
  // optional bool debug = 18;
  if (has_debug()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(18, this->debug(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int PbJobSearchQuery::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int32 offset = 1;
    if (has_offset()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->offset());
    }
    
    // optional int32 count = 2;
    if (has_count()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->count());
    }
    
    // required bytes xapian_query_blob = 3;
    if (has_xapian_query_blob()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->xapian_query_blob());
    }
    
    // optional int64 searcher_uid = 5;
    if (has_searcher_uid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->searcher_uid());
    }
    
    // optional int32 search_type = 9;
    if (has_search_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->search_type());
    }
    
  }
  if (_has_bits_[12 / 32] & (0xffu << (12 % 32))) {
    // optional int32 task_type = 17;
    if (has_task_type()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->task_type());
    }
    
    // optional bool debug = 18;
    if (has_debug()) {
      total_size += 2 + 1;
    }
    
  }
  // repeated int64 d1_uid = 6;
  {
    int data_size = 0;
    for (int i = 0; i < this->d1_uid_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int64Size(this->d1_uid(i));
    }
    total_size += 1 * this->d1_uid_size() + data_size;
  }
  
  // repeated int64 d2_uid = 7;
  {
    int data_size = 0;
    for (int i = 0; i < this->d2_uid_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int64Size(this->d2_uid(i));
    }
    total_size += 1 * this->d2_uid_size() + data_size;
  }
  
  // repeated .job_search.PbJobSearchQuery.TermExpansion te = 8;
  total_size += 1 * this->te_size();
  for (int i = 0; i < this->te_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->te(i));
  }
  
  // repeated uint64 stats_com_term = 13;
  {
    int data_size = 0;
    for (int i = 0; i < this->stats_com_term_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        UInt64Size(this->stats_com_term(i));
    }
    total_size += 1 * this->stats_com_term_size() + data_size;
  }
  
  // repeated uint64 stats_job_term = 14;
  {
    int data_size = 0;
    for (int i = 0; i < this->stats_job_term_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        UInt64Size(this->stats_job_term(i));
    }
    total_size += 1 * this->stats_job_term_size() + data_size;
  }
  
  // repeated uint64 stats_tag_term = 15;
  {
    int data_size = 0;
    for (int i = 0; i < this->stats_tag_term_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        UInt64Size(this->stats_tag_term(i));
    }
    total_size += 1 * this->stats_tag_term_size() + data_size;
  }
  
  // repeated uint64 stats_sch_term = 16;
  {
    int data_size = 0;
    for (int i = 0; i < this->stats_sch_term_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        UInt64Size(this->stats_sch_term(i));
    }
    total_size += 2 * this->stats_sch_term_size() + data_size;
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PbJobSearchQuery::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const PbJobSearchQuery* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const PbJobSearchQuery*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void PbJobSearchQuery::MergeFrom(const PbJobSearchQuery& from) {
  GOOGLE_CHECK_NE(&from, this);
  d1_uid_.MergeFrom(from.d1_uid_);
  d2_uid_.MergeFrom(from.d2_uid_);
  te_.MergeFrom(from.te_);
  stats_com_term_.MergeFrom(from.stats_com_term_);
  stats_job_term_.MergeFrom(from.stats_job_term_);
  stats_tag_term_.MergeFrom(from.stats_tag_term_);
  stats_sch_term_.MergeFrom(from.stats_sch_term_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_offset()) {
      set_offset(from.offset());
    }
    if (from.has_count()) {
      set_count(from.count());
    }
    if (from.has_xapian_query_blob()) {
      set_xapian_query_blob(from.xapian_query_blob());
    }
    if (from.has_searcher_uid()) {
      set_searcher_uid(from.searcher_uid());
    }
    if (from.has_search_type()) {
      set_search_type(from.search_type());
    }
  }
  if (from._has_bits_[12 / 32] & (0xffu << (12 % 32))) {
    if (from.has_task_type()) {
      set_task_type(from.task_type());
    }
    if (from.has_debug()) {
      set_debug(from.debug());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void PbJobSearchQuery::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PbJobSearchQuery::CopyFrom(const PbJobSearchQuery& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PbJobSearchQuery::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000004) != 0x00000004) return false;
  
  for (int i = 0; i < te_size(); i++) {
    if (!this->te(i).IsInitialized()) return false;
  }
  return true;
}

void PbJobSearchQuery::Swap(PbJobSearchQuery* other) {
  if (other != this) {
    std::swap(offset_, other->offset_);
    std::swap(count_, other->count_);
    std::swap(xapian_query_blob_, other->xapian_query_blob_);
    std::swap(searcher_uid_, other->searcher_uid_);
    d1_uid_.Swap(&other->d1_uid_);
    d2_uid_.Swap(&other->d2_uid_);
    te_.Swap(&other->te_);
    std::swap(search_type_, other->search_type_);
    stats_com_term_.Swap(&other->stats_com_term_);
    stats_job_term_.Swap(&other->stats_job_term_);
    stats_tag_term_.Swap(&other->stats_tag_term_);
    stats_sch_term_.Swap(&other->stats_sch_term_);
    std::swap(task_type_, other->task_type_);
    std::swap(debug_, other->debug_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata PbJobSearchQuery::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PbJobSearchQuery_descriptor_;
  metadata.reflection = PbJobSearchQuery_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace job_search

// @@protoc_insertion_point(global_scope)
