// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserSearchResult.proto

#ifndef PROTOBUF_UserSearchResult_2eproto__INCLUDED
#define PROTOBUF_UserSearchResult_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace user_search {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_UserSearchResult_2eproto();
void protobuf_AssignDesc_UserSearchResult_2eproto();
void protobuf_ShutdownFile_UserSearchResult_2eproto();

class UserSearchResult;
class UserSearchResult_ResultItem;
class UserSearchResult_StatsItem;

// ===================================================================

class UserSearchResult_ResultItem : public ::google::protobuf::Message {
 public:
  UserSearchResult_ResultItem();
  virtual ~UserSearchResult_ResultItem();
  
  UserSearchResult_ResultItem(const UserSearchResult_ResultItem& from);
  
  inline UserSearchResult_ResultItem& operator=(const UserSearchResult_ResultItem& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const UserSearchResult_ResultItem& default_instance();
  
  void Swap(UserSearchResult_ResultItem* other);
  
  // implements Message ----------------------------------------------
  
  UserSearchResult_ResultItem* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UserSearchResult_ResultItem& from);
  void MergeFrom(const UserSearchResult_ResultItem& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional int64 uid = 1;
  inline bool has_uid() const;
  inline void clear_uid();
  static const int kUidFieldNumber = 1;
  inline ::google::protobuf::int64 uid() const;
  inline void set_uid(::google::protobuf::int64 value);
  
  // optional double score = 2;
  inline bool has_score() const;
  inline void clear_score();
  static const int kScoreFieldNumber = 2;
  inline double score() const;
  inline void set_score(double value);
  
  // optional int32 link_distance = 3;
  inline bool has_link_distance() const;
  inline void clear_link_distance();
  static const int kLinkDistanceFieldNumber = 3;
  inline ::google::protobuf::int32 link_distance() const;
  inline void set_link_distance(::google::protobuf::int32 value);
  
  // optional bytes debug_data = 4;
  inline bool has_debug_data() const;
  inline void clear_debug_data();
  static const int kDebugDataFieldNumber = 4;
  inline const ::std::string& debug_data() const;
  inline void set_debug_data(const ::std::string& value);
  inline void set_debug_data(const char* value);
  inline void set_debug_data(const void* value, size_t size);
  inline ::std::string* mutable_debug_data();
  inline ::std::string* release_debug_data();
  
  // @@protoc_insertion_point(class_scope:user_search.UserSearchResult.ResultItem)
 private:
  inline void set_has_uid();
  inline void clear_has_uid();
  inline void set_has_score();
  inline void clear_has_score();
  inline void set_has_link_distance();
  inline void clear_has_link_distance();
  inline void set_has_debug_data();
  inline void clear_has_debug_data();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int64 uid_;
  double score_;
  ::std::string* debug_data_;
  ::google::protobuf::int32 link_distance_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];
  
  friend void  protobuf_AddDesc_UserSearchResult_2eproto();
  friend void protobuf_AssignDesc_UserSearchResult_2eproto();
  friend void protobuf_ShutdownFile_UserSearchResult_2eproto();
  
  void InitAsDefaultInstance();
  static UserSearchResult_ResultItem* default_instance_;
};
// -------------------------------------------------------------------

class UserSearchResult_StatsItem : public ::google::protobuf::Message {
 public:
  UserSearchResult_StatsItem();
  virtual ~UserSearchResult_StatsItem();
  
  UserSearchResult_StatsItem(const UserSearchResult_StatsItem& from);
  
  inline UserSearchResult_StatsItem& operator=(const UserSearchResult_StatsItem& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const UserSearchResult_StatsItem& default_instance();
  
  void Swap(UserSearchResult_StatsItem* other);
  
  // implements Message ----------------------------------------------
  
  UserSearchResult_StatsItem* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UserSearchResult_StatsItem& from);
  void MergeFrom(const UserSearchResult_StatsItem& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional bytes stats_type = 1;
  inline bool has_stats_type() const;
  inline void clear_stats_type();
  static const int kStatsTypeFieldNumber = 1;
  inline const ::std::string& stats_type() const;
  inline void set_stats_type(const ::std::string& value);
  inline void set_stats_type(const char* value);
  inline void set_stats_type(const void* value, size_t size);
  inline ::std::string* mutable_stats_type();
  inline ::std::string* release_stats_type();
  
  // optional uint64 stats_key = 2;
  inline bool has_stats_key() const;
  inline void clear_stats_key();
  static const int kStatsKeyFieldNumber = 2;
  inline ::google::protobuf::uint64 stats_key() const;
  inline void set_stats_key(::google::protobuf::uint64 value);
  
  // optional bytes stats_name = 4;
  inline bool has_stats_name() const;
  inline void clear_stats_name();
  static const int kStatsNameFieldNumber = 4;
  inline const ::std::string& stats_name() const;
  inline void set_stats_name(const ::std::string& value);
  inline void set_stats_name(const char* value);
  inline void set_stats_name(const void* value, size_t size);
  inline ::std::string* mutable_stats_name();
  inline ::std::string* release_stats_name();
  
  // optional uint64 stats_value = 3;
  inline bool has_stats_value() const;
  inline void clear_stats_value();
  static const int kStatsValueFieldNumber = 3;
  inline ::google::protobuf::uint64 stats_value() const;
  inline void set_stats_value(::google::protobuf::uint64 value);
  
  // @@protoc_insertion_point(class_scope:user_search.UserSearchResult.StatsItem)
 private:
  inline void set_has_stats_type();
  inline void clear_has_stats_type();
  inline void set_has_stats_key();
  inline void clear_has_stats_key();
  inline void set_has_stats_name();
  inline void clear_has_stats_name();
  inline void set_has_stats_value();
  inline void clear_has_stats_value();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* stats_type_;
  ::google::protobuf::uint64 stats_key_;
  ::std::string* stats_name_;
  ::google::protobuf::uint64 stats_value_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];
  
  friend void  protobuf_AddDesc_UserSearchResult_2eproto();
  friend void protobuf_AssignDesc_UserSearchResult_2eproto();
  friend void protobuf_ShutdownFile_UserSearchResult_2eproto();
  
  void InitAsDefaultInstance();
  static UserSearchResult_StatsItem* default_instance_;
};
// -------------------------------------------------------------------

class UserSearchResult : public ::google::protobuf::Message {
 public:
  UserSearchResult();
  virtual ~UserSearchResult();
  
  UserSearchResult(const UserSearchResult& from);
  
  inline UserSearchResult& operator=(const UserSearchResult& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const UserSearchResult& default_instance();
  
  void Swap(UserSearchResult* other);
  
  // implements Message ----------------------------------------------
  
  UserSearchResult* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UserSearchResult& from);
  void MergeFrom(const UserSearchResult& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef UserSearchResult_ResultItem ResultItem;
  typedef UserSearchResult_StatsItem StatsItem;
  
  // accessors -------------------------------------------------------
  
  // optional int32 offset = 1;
  inline bool has_offset() const;
  inline void clear_offset();
  static const int kOffsetFieldNumber = 1;
  inline ::google::protobuf::int32 offset() const;
  inline void set_offset(::google::protobuf::int32 value);
  
  // optional int32 count = 2;
  inline bool has_count() const;
  inline void clear_count();
  static const int kCountFieldNumber = 2;
  inline ::google::protobuf::int32 count() const;
  inline void set_count(::google::protobuf::int32 value);
  
  // optional int32 total_estimated = 3;
  inline bool has_total_estimated() const;
  inline void clear_total_estimated();
  static const int kTotalEstimatedFieldNumber = 3;
  inline ::google::protobuf::int32 total_estimated() const;
  inline void set_total_estimated(::google::protobuf::int32 value);
  
  // repeated .user_search.UserSearchResult.ResultItem result_item = 4;
  inline int result_item_size() const;
  inline void clear_result_item();
  static const int kResultItemFieldNumber = 4;
  inline const ::user_search::UserSearchResult_ResultItem& result_item(int index) const;
  inline ::user_search::UserSearchResult_ResultItem* mutable_result_item(int index);
  inline ::user_search::UserSearchResult_ResultItem* add_result_item();
  inline const ::google::protobuf::RepeatedPtrField< ::user_search::UserSearchResult_ResultItem >&
      result_item() const;
  inline ::google::protobuf::RepeatedPtrField< ::user_search::UserSearchResult_ResultItem >*
      mutable_result_item();
  
  // repeated .user_search.UserSearchResult.StatsItem stats_item = 5;
  inline int stats_item_size() const;
  inline void clear_stats_item();
  static const int kStatsItemFieldNumber = 5;
  inline const ::user_search::UserSearchResult_StatsItem& stats_item(int index) const;
  inline ::user_search::UserSearchResult_StatsItem* mutable_stats_item(int index);
  inline ::user_search::UserSearchResult_StatsItem* add_stats_item();
  inline const ::google::protobuf::RepeatedPtrField< ::user_search::UserSearchResult_StatsItem >&
      stats_item() const;
  inline ::google::protobuf::RepeatedPtrField< ::user_search::UserSearchResult_StatsItem >*
      mutable_stats_item();
  
  // @@protoc_insertion_point(class_scope:user_search.UserSearchResult)
 private:
  inline void set_has_offset();
  inline void clear_has_offset();
  inline void set_has_count();
  inline void clear_has_count();
  inline void set_has_total_estimated();
  inline void clear_has_total_estimated();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 offset_;
  ::google::protobuf::int32 count_;
  ::google::protobuf::RepeatedPtrField< ::user_search::UserSearchResult_ResultItem > result_item_;
  ::google::protobuf::RepeatedPtrField< ::user_search::UserSearchResult_StatsItem > stats_item_;
  ::google::protobuf::int32 total_estimated_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];
  
  friend void  protobuf_AddDesc_UserSearchResult_2eproto();
  friend void protobuf_AssignDesc_UserSearchResult_2eproto();
  friend void protobuf_ShutdownFile_UserSearchResult_2eproto();
  
  void InitAsDefaultInstance();
  static UserSearchResult* default_instance_;
};
// ===================================================================


// ===================================================================

// UserSearchResult_ResultItem

// optional int64 uid = 1;
inline bool UserSearchResult_ResultItem::has_uid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UserSearchResult_ResultItem::set_has_uid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UserSearchResult_ResultItem::clear_has_uid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UserSearchResult_ResultItem::clear_uid() {
  uid_ = GOOGLE_LONGLONG(0);
  clear_has_uid();
}
inline ::google::protobuf::int64 UserSearchResult_ResultItem::uid() const {
  return uid_;
}
inline void UserSearchResult_ResultItem::set_uid(::google::protobuf::int64 value) {
  set_has_uid();
  uid_ = value;
}

// optional double score = 2;
inline bool UserSearchResult_ResultItem::has_score() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UserSearchResult_ResultItem::set_has_score() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UserSearchResult_ResultItem::clear_has_score() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UserSearchResult_ResultItem::clear_score() {
  score_ = 0;
  clear_has_score();
}
inline double UserSearchResult_ResultItem::score() const {
  return score_;
}
inline void UserSearchResult_ResultItem::set_score(double value) {
  set_has_score();
  score_ = value;
}

// optional int32 link_distance = 3;
inline bool UserSearchResult_ResultItem::has_link_distance() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void UserSearchResult_ResultItem::set_has_link_distance() {
  _has_bits_[0] |= 0x00000004u;
}
inline void UserSearchResult_ResultItem::clear_has_link_distance() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void UserSearchResult_ResultItem::clear_link_distance() {
  link_distance_ = 0;
  clear_has_link_distance();
}
inline ::google::protobuf::int32 UserSearchResult_ResultItem::link_distance() const {
  return link_distance_;
}
inline void UserSearchResult_ResultItem::set_link_distance(::google::protobuf::int32 value) {
  set_has_link_distance();
  link_distance_ = value;
}

// optional bytes debug_data = 4;
inline bool UserSearchResult_ResultItem::has_debug_data() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void UserSearchResult_ResultItem::set_has_debug_data() {
  _has_bits_[0] |= 0x00000008u;
}
inline void UserSearchResult_ResultItem::clear_has_debug_data() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void UserSearchResult_ResultItem::clear_debug_data() {
  if (debug_data_ != &::google::protobuf::internal::kEmptyString) {
    debug_data_->clear();
  }
  clear_has_debug_data();
}
inline const ::std::string& UserSearchResult_ResultItem::debug_data() const {
  return *debug_data_;
}
inline void UserSearchResult_ResultItem::set_debug_data(const ::std::string& value) {
  set_has_debug_data();
  if (debug_data_ == &::google::protobuf::internal::kEmptyString) {
    debug_data_ = new ::std::string;
  }
  debug_data_->assign(value);
}
inline void UserSearchResult_ResultItem::set_debug_data(const char* value) {
  set_has_debug_data();
  if (debug_data_ == &::google::protobuf::internal::kEmptyString) {
    debug_data_ = new ::std::string;
  }
  debug_data_->assign(value);
}
inline void UserSearchResult_ResultItem::set_debug_data(const void* value, size_t size) {
  set_has_debug_data();
  if (debug_data_ == &::google::protobuf::internal::kEmptyString) {
    debug_data_ = new ::std::string;
  }
  debug_data_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* UserSearchResult_ResultItem::mutable_debug_data() {
  set_has_debug_data();
  if (debug_data_ == &::google::protobuf::internal::kEmptyString) {
    debug_data_ = new ::std::string;
  }
  return debug_data_;
}
inline ::std::string* UserSearchResult_ResultItem::release_debug_data() {
  clear_has_debug_data();
  if (debug_data_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = debug_data_;
    debug_data_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// -------------------------------------------------------------------

// UserSearchResult_StatsItem

// optional bytes stats_type = 1;
inline bool UserSearchResult_StatsItem::has_stats_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UserSearchResult_StatsItem::set_has_stats_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UserSearchResult_StatsItem::clear_has_stats_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UserSearchResult_StatsItem::clear_stats_type() {
  if (stats_type_ != &::google::protobuf::internal::kEmptyString) {
    stats_type_->clear();
  }
  clear_has_stats_type();
}
inline const ::std::string& UserSearchResult_StatsItem::stats_type() const {
  return *stats_type_;
}
inline void UserSearchResult_StatsItem::set_stats_type(const ::std::string& value) {
  set_has_stats_type();
  if (stats_type_ == &::google::protobuf::internal::kEmptyString) {
    stats_type_ = new ::std::string;
  }
  stats_type_->assign(value);
}
inline void UserSearchResult_StatsItem::set_stats_type(const char* value) {
  set_has_stats_type();
  if (stats_type_ == &::google::protobuf::internal::kEmptyString) {
    stats_type_ = new ::std::string;
  }
  stats_type_->assign(value);
}
inline void UserSearchResult_StatsItem::set_stats_type(const void* value, size_t size) {
  set_has_stats_type();
  if (stats_type_ == &::google::protobuf::internal::kEmptyString) {
    stats_type_ = new ::std::string;
  }
  stats_type_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* UserSearchResult_StatsItem::mutable_stats_type() {
  set_has_stats_type();
  if (stats_type_ == &::google::protobuf::internal::kEmptyString) {
    stats_type_ = new ::std::string;
  }
  return stats_type_;
}
inline ::std::string* UserSearchResult_StatsItem::release_stats_type() {
  clear_has_stats_type();
  if (stats_type_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = stats_type_;
    stats_type_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// optional uint64 stats_key = 2;
inline bool UserSearchResult_StatsItem::has_stats_key() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UserSearchResult_StatsItem::set_has_stats_key() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UserSearchResult_StatsItem::clear_has_stats_key() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UserSearchResult_StatsItem::clear_stats_key() {
  stats_key_ = GOOGLE_ULONGLONG(0);
  clear_has_stats_key();
}
inline ::google::protobuf::uint64 UserSearchResult_StatsItem::stats_key() const {
  return stats_key_;
}
inline void UserSearchResult_StatsItem::set_stats_key(::google::protobuf::uint64 value) {
  set_has_stats_key();
  stats_key_ = value;
}

// optional bytes stats_name = 4;
inline bool UserSearchResult_StatsItem::has_stats_name() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void UserSearchResult_StatsItem::set_has_stats_name() {
  _has_bits_[0] |= 0x00000004u;
}
inline void UserSearchResult_StatsItem::clear_has_stats_name() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void UserSearchResult_StatsItem::clear_stats_name() {
  if (stats_name_ != &::google::protobuf::internal::kEmptyString) {
    stats_name_->clear();
  }
  clear_has_stats_name();
}
inline const ::std::string& UserSearchResult_StatsItem::stats_name() const {
  return *stats_name_;
}
inline void UserSearchResult_StatsItem::set_stats_name(const ::std::string& value) {
  set_has_stats_name();
  if (stats_name_ == &::google::protobuf::internal::kEmptyString) {
    stats_name_ = new ::std::string;
  }
  stats_name_->assign(value);
}
inline void UserSearchResult_StatsItem::set_stats_name(const char* value) {
  set_has_stats_name();
  if (stats_name_ == &::google::protobuf::internal::kEmptyString) {
    stats_name_ = new ::std::string;
  }
  stats_name_->assign(value);
}
inline void UserSearchResult_StatsItem::set_stats_name(const void* value, size_t size) {
  set_has_stats_name();
  if (stats_name_ == &::google::protobuf::internal::kEmptyString) {
    stats_name_ = new ::std::string;
  }
  stats_name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* UserSearchResult_StatsItem::mutable_stats_name() {
  set_has_stats_name();
  if (stats_name_ == &::google::protobuf::internal::kEmptyString) {
    stats_name_ = new ::std::string;
  }
  return stats_name_;
}
inline ::std::string* UserSearchResult_StatsItem::release_stats_name() {
  clear_has_stats_name();
  if (stats_name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = stats_name_;
    stats_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// optional uint64 stats_value = 3;
inline bool UserSearchResult_StatsItem::has_stats_value() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void UserSearchResult_StatsItem::set_has_stats_value() {
  _has_bits_[0] |= 0x00000008u;
}
inline void UserSearchResult_StatsItem::clear_has_stats_value() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void UserSearchResult_StatsItem::clear_stats_value() {
  stats_value_ = GOOGLE_ULONGLONG(0);
  clear_has_stats_value();
}
inline ::google::protobuf::uint64 UserSearchResult_StatsItem::stats_value() const {
  return stats_value_;
}
inline void UserSearchResult_StatsItem::set_stats_value(::google::protobuf::uint64 value) {
  set_has_stats_value();
  stats_value_ = value;
}

// -------------------------------------------------------------------

// UserSearchResult

// optional int32 offset = 1;
inline bool UserSearchResult::has_offset() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UserSearchResult::set_has_offset() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UserSearchResult::clear_has_offset() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UserSearchResult::clear_offset() {
  offset_ = 0;
  clear_has_offset();
}
inline ::google::protobuf::int32 UserSearchResult::offset() const {
  return offset_;
}
inline void UserSearchResult::set_offset(::google::protobuf::int32 value) {
  set_has_offset();
  offset_ = value;
}

// optional int32 count = 2;
inline bool UserSearchResult::has_count() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UserSearchResult::set_has_count() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UserSearchResult::clear_has_count() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UserSearchResult::clear_count() {
  count_ = 0;
  clear_has_count();
}
inline ::google::protobuf::int32 UserSearchResult::count() const {
  return count_;
}
inline void UserSearchResult::set_count(::google::protobuf::int32 value) {
  set_has_count();
  count_ = value;
}

// optional int32 total_estimated = 3;
inline bool UserSearchResult::has_total_estimated() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void UserSearchResult::set_has_total_estimated() {
  _has_bits_[0] |= 0x00000004u;
}
inline void UserSearchResult::clear_has_total_estimated() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void UserSearchResult::clear_total_estimated() {
  total_estimated_ = 0;
  clear_has_total_estimated();
}
inline ::google::protobuf::int32 UserSearchResult::total_estimated() const {
  return total_estimated_;
}
inline void UserSearchResult::set_total_estimated(::google::protobuf::int32 value) {
  set_has_total_estimated();
  total_estimated_ = value;
}

// repeated .user_search.UserSearchResult.ResultItem result_item = 4;
inline int UserSearchResult::result_item_size() const {
  return result_item_.size();
}
inline void UserSearchResult::clear_result_item() {
  result_item_.Clear();
}
inline const ::user_search::UserSearchResult_ResultItem& UserSearchResult::result_item(int index) const {
  return result_item_.Get(index);
}
inline ::user_search::UserSearchResult_ResultItem* UserSearchResult::mutable_result_item(int index) {
  return result_item_.Mutable(index);
}
inline ::user_search::UserSearchResult_ResultItem* UserSearchResult::add_result_item() {
  return result_item_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::user_search::UserSearchResult_ResultItem >&
UserSearchResult::result_item() const {
  return result_item_;
}
inline ::google::protobuf::RepeatedPtrField< ::user_search::UserSearchResult_ResultItem >*
UserSearchResult::mutable_result_item() {
  return &result_item_;
}

// repeated .user_search.UserSearchResult.StatsItem stats_item = 5;
inline int UserSearchResult::stats_item_size() const {
  return stats_item_.size();
}
inline void UserSearchResult::clear_stats_item() {
  stats_item_.Clear();
}
inline const ::user_search::UserSearchResult_StatsItem& UserSearchResult::stats_item(int index) const {
  return stats_item_.Get(index);
}
inline ::user_search::UserSearchResult_StatsItem* UserSearchResult::mutable_stats_item(int index) {
  return stats_item_.Mutable(index);
}
inline ::user_search::UserSearchResult_StatsItem* UserSearchResult::add_stats_item() {
  return stats_item_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::user_search::UserSearchResult_StatsItem >&
UserSearchResult::stats_item() const {
  return stats_item_;
}
inline ::google::protobuf::RepeatedPtrField< ::user_search::UserSearchResult_StatsItem >*
UserSearchResult::mutable_stats_item() {
  return &stats_item_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace user_search

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_UserSearchResult_2eproto__INCLUDED
